<?php
/**
 * Gutenverse Single Portfolio content.
 */
return array(
	'title'      => __( 'Gutenverse Single Portfolio', 'photology' ),
	'categories' => array( 'photology-gutenverse' ),
	'content'    => '
            <!-- wp:gutenverse/section {"width":"1170","elementId":"guten-UWvKNT","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40"}}}} -->
            <div class="section-wrapper" data-id="UWvKNT"><script>var topUWvKNT = {"Desktop":{"point":"0","unit":"px"}};var bottomUWvKNT = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-UWvKNT layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-H1ueux"} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-H1ueux"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="H1ueux"><script>var topH1ueux = {"Desktop":{"point":"0","unit":"px"}};var bottomH1ueux = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"width":"1170","isChild":true,"gap":"no","elementId":"guten-TLXhOM","margin":{"Desktop":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":[]}} -->
            <div class="section-wrapper" data-id="TLXhOM"><script>var topTLXhOM = {"Desktop":{"point":"0","unit":"px"}};var bottomTLXhOM = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-TLXhOM layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-OAt4ad"} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-OAt4ad"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="OAt4ad"><script>var topOAt4ad = {"Desktop":{"point":"0","unit":"px"}};var bottomOAt4ad = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-5dbGYA","imgSrc":{"media":{"imageId":41,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( PHOTOLOGY_URI ) . '/assets/img/mann-love-couple-wedding-bride-groom-736332-pxhere.com-150x150.jpg","orientation":"landscape"},"medium":{"height":214,"width":300,"url":"' . esc_url( PHOTOLOGY_URI ) . '/assets/img/mann-love-couple-wedding-bride-groom-736332-pxhere.com-300x214.jpg","orientation":"landscape"},"large":{"height":731,"width":1024,"url":"' . esc_url( PHOTOLOGY_URI ) . '/assets/img/mann-love-couple-wedding-bride-groom-736332-pxhere.com-1024x731.jpg","orientation":"landscape"},"full":{"url":"' . esc_url( PHOTOLOGY_URI ) . '/assets/img/mann-love-couple-wedding-bride-groom-736332-pxhere.com.jpg","height":800,"width":1120,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"unit":"%","point":"100"}},"height":{"Desktop":{"unit":"px","point":""}},"imgBorder":{"radius":{"Desktop":[]}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"slow"}} -->
            <div class="wp-block-gutenverse-image guten-element guten-image guten-5dbGYA animated guten-element-hide slow desktop-fadeInUp"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( PHOTOLOGY_URI ) . '/assets/img/mann-love-couple-wedding-bride-groom-736332-pxhere.com.jpg" height="800" width="1120"/></a></div>
            <!-- /wp:gutenverse/image --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->
            
            <!-- wp:gutenverse/section {"width":"1170","isChild":true,"gap":"no","elementId":"guten-QBCZ3o","margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}},"Tablet":{"unit":"px","dimension":{"top":"30"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]}} -->
            <div class="section-wrapper" data-id="QBCZ3o"><script>var topQBCZ3o = {"Desktop":{"point":"0","unit":"px"}};var bottomQBCZ3o = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-QBCZ3o layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-b0aVzs","margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Tablet":{"unit":"px","dimension":{"right":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-b0aVzs"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="b0aVzs"><script>var topb0aVzs = {"Desktop":{"point":"0","unit":"px"}};var bottomb0aVzs = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-jZzHeK","imgSrc":{"media":{"imageId":78,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( PHOTOLOGY_URI ) . '/assets/img/man-woman-white-photography-love-heart-772699-pxhere.com-150x150.jpg","orientation":"landscape"},"medium":{"height":200,"width":300,"url":"' . esc_url( PHOTOLOGY_URI ) . '/assets/img/man-woman-white-photography-love-heart-772699-pxhere.com-300x200.jpg","orientation":"landscape"},"large":{"height":682,"width":1024,"url":"' . esc_url( PHOTOLOGY_URI ) . '/assets/img/man-woman-white-photography-love-heart-772699-pxhere.com-1024x682.jpg","orientation":"landscape"},"full":{"url":"' . esc_url( PHOTOLOGY_URI ) . '/assets/img/man-woman-white-photography-love-heart-772699-pxhere.com.jpg","height":1278,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","imgFilter":{"saturation":"0"},"imgBorder":{"radius":{"Desktop":[]}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"slow"}} -->
            <div class="wp-block-gutenverse-image guten-element guten-image guten-jZzHeK animated guten-element-hide slow desktop-fadeInLeft"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( PHOTOLOGY_URI ) . '/assets/img/man-woman-white-photography-love-heart-772699-pxhere.com.jpg" height="1278" width="1920"/></a></div>
            <!-- /wp:gutenverse/image --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-04GO5b","margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Tablet":{"unit":"px","dimension":{"left":"15"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-04GO5b"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="04GO5b"><script>var top04GO5b = {"Desktop":{"point":"0","unit":"px"}};var bottom04GO5b = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-UgsIOp","imgSrc":{"media":{"imageId":77,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( PHOTOLOGY_URI ) . '/assets/img/blossom-plant-flower-purple-petal-rose-708173-pxhere.com-150x150.jpg","orientation":"landscape"},"medium":{"height":199,"width":300,"url":"' . esc_url( PHOTOLOGY_URI ) . '/assets/img/blossom-plant-flower-purple-petal-rose-708173-pxhere.com-300x199.jpg","orientation":"landscape"},"large":{"height":678,"width":1024,"url":"' . esc_url( PHOTOLOGY_URI ) . '/assets/img/blossom-plant-flower-purple-petal-rose-708173-pxhere.com-1024x678.jpg","orientation":"landscape"},"full":{"url":"' . esc_url( PHOTOLOGY_URI ) . '/assets/img/blossom-plant-flower-purple-petal-rose-708173-pxhere.com.jpg","height":1272,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","imgFilter":{"saturation":"0"},"imgBorder":{"radius":{"Desktop":[]}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"slow"}} -->
            <div class="wp-block-gutenverse-image guten-element guten-image guten-UgsIOp animated guten-element-hide slow desktop-fadeInRight"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( PHOTOLOGY_URI ) . '/assets/img/blossom-plant-flower-purple-petal-rose-708173-pxhere.com.jpg" height="1272" width="1920"/></a></div>
            <!-- /wp:gutenverse/image --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->
            
            <!-- wp:gutenverse/section {"width":"1000","isChild":true,"gap":"no","elementId":"guten-C9iVQ3","margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"40","bottom":"","left":"40"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0"}}}} -->
            <div class="section-wrapper" data-id="C9iVQ3"><script>var topC9iVQ3 = {"Desktop":{"point":"0","unit":"px"}};var bottomC9iVQ3 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-C9iVQ3 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-pUnwNI","margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}}},"padding":{"Desktop":[]}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-pUnwNI"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="pUnwNI"><script>var toppUnwNI = {"Desktop":{"point":"0","unit":"px"}};var bottompUnwNI = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-NLL8ZI","color":{"r":52,"g":51,"b":51,"a":1},"typography":{"font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"400"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"slow"}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-NLL8ZI animated guten-element-hide slow desktop-fadeInLeft">Michael &amp; Gina Wedding Ceremony</h2>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/text-editor {"elementId":"guten-eM8mxi","textColor":{"r":139,"g":139,"b":139,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"}} -->
            <div class="guten-element gutenverse-text-editor guten-eM8mxi"><div class="text-content-inner"><!-- wp:paragraph -->
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
            <!-- /wp:paragraph --></div></div>
            <!-- /wp:gutenverse/text-editor -->
            
            <!-- wp:gutenverse/text-editor {"elementId":"guten-NvRodV","textColor":{"r":139,"g":139,"b":139,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"}} -->
            <div class="guten-element gutenverse-text-editor guten-NvRodV"><div class="text-content-inner"><!-- wp:paragraph -->
            <p>Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore.</p>
            <!-- /wp:paragraph --></div></div>
            <!-- /wp:gutenverse/text-editor --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-45QFb6","margin":{"Desktop":{"unit":"px","dimension":{"left":"100"}},"Tablet":{"unit":"px","dimension":{"right":"","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-45QFb6"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="45QFb6"><script>var top45QFb6 = {"Desktop":{"point":"0","unit":"px"}};var bottom45QFb6 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-fShHpy"} -->
            <div class="section-wrapper" data-id="fShHpy"><script>var topfShHpy = {"Desktop":{"point":"0","unit":"px"}};var bottomfShHpy = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-fShHpy layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33},"elementId":"guten-wjg2K2"} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-wjg2K2"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="wjg2K2"><script>var topwjg2K2 = {"Desktop":{"point":"0","unit":"px"}};var bottomwjg2K2 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-WkxJSg","color":{"r":52,"g":51,"b":51,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"spacing":{"Desktop":""},"weight":"300"}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-WkxJSg">Client : </h2>
            <!-- /wp:gutenverse/heading --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":67},"elementId":"guten-WINEDf"} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-WINEDf"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="WINEDf"><script>var topWINEDf = {"Desktop":{"point":"0","unit":"px"}};var bottomWINEDf = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-4Xgs5I","type":6,"color":{"r":139,"g":139,"b":139,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"300"}} -->
            <h6 class="wp-block-gutenverse-heading guten-element guten-4Xgs5I">Michael &amp; Gina</h6>
            <!-- /wp:gutenverse/heading --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->
            
            <!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-a36SRe"} -->
            <div class="section-wrapper" data-id="a36SRe"><script>var topa36SRe = {"Desktop":{"point":"0","unit":"px"}};var bottoma36SRe = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-a36SRe layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33},"elementId":"guten-GOEXYw"} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-GOEXYw"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="GOEXYw"><script>var topGOEXYw = {"Desktop":{"point":"0","unit":"px"}};var bottomGOEXYw = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-VRcmHG","color":{"r":52,"g":51,"b":51,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"spacing":{"Desktop":""},"weight":"300"}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-VRcmHG">Date : </h2>
            <!-- /wp:gutenverse/heading --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":67},"elementId":"guten-sBYjm5"} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-sBYjm5"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="sBYjm5"><script>var topsBYjm5 = {"Desktop":{"point":"0","unit":"px"}};var bottomsBYjm5 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-fwA1R8","type":6,"color":{"r":139,"g":139,"b":139,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"300"}} -->
            <h6 class="wp-block-gutenverse-heading guten-element guten-fwA1R8">24 August 2021</h6>
            <!-- /wp:gutenverse/heading --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->
            
            <!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-ConBeq"} -->
            <div class="section-wrapper" data-id="ConBeq"><script>var topConBeq = {"Desktop":{"point":"0","unit":"px"}};var bottomConBeq = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-ConBeq layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33},"elementId":"guten-897Ggs"} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-897Ggs"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="897Ggs"><script>var top897Ggs = {"Desktop":{"point":"0","unit":"px"}};var bottom897Ggs = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-bZNdge","color":{"r":52,"g":51,"b":51,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"spacing":{"Desktop":""},"weight":"300"}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-bZNdge">Category : </h2>
            <!-- /wp:gutenverse/heading --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":67},"elementId":"guten-LHnqhJ"} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-LHnqhJ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="LHnqhJ"><script>var topLHnqhJ = {"Desktop":{"point":"0","unit":"px"}};var bottomLHnqhJ = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-H9cVgo","type":6,"color":{"r":139,"g":139,"b":139,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"300"}} -->
            <h6 class="wp-block-gutenverse-heading guten-element guten-H9cVgo">Wedding Photography</h6>
            <!-- /wp:gutenverse/heading --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->
            
            <!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-6SGMQA"} -->
            <div class="section-wrapper" data-id="6SGMQA"><script>var top6SGMQA = {"Desktop":{"point":"0","unit":"px"}};var bottom6SGMQA = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-6SGMQA layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33,"Mobile":null},"elementId":"guten-HTKzdW"} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-HTKzdW"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="HTKzdW"><script>var topHTKzdW = {"Desktop":{"point":"0","unit":"px"}};var bottomHTKzdW = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-d0dVbE","color":{"r":52,"g":51,"b":51,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"spacing":{"Desktop":""},"weight":"300"}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-d0dVbE">Share This : </h2>
            <!-- /wp:gutenverse/heading --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":67},"elementId":"guten-G9FGlM"} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-G9FGlM"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="G9FGlM"><script>var topG9FGlM = {"Desktop":{"point":"0","unit":"px"}};var bottomG9FGlM = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/social-share {"elementId":"guten-HMOLRx","iconColor":{"r":255,"g":255,"b":255,"a":1},"iconBackgroundColor":{"r":145,"g":108,"b":61,"a":1},"borderType":{"radius":{"Desktop":{"unit":"%","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"alignment":{"Desktop":"flex-start","Tablet":"center","Mobile":"flex-start"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}}} -->
            <div class="guten-element guten-social-share guten-HMOLRx guten-social-share"><!-- wp:gutenverse/social-share-facebook {"elementId":"guten-YmVdz6","showText":false} /-->
            
            <!-- wp:gutenverse/social-share-twitter {"elementId":"guten-h9N91v","showText":false} /-->
            
            <!-- wp:gutenverse/social-share-whatsapp {"elementId":"guten-JwpZ0K","showText":false} /--></div>
            <!-- /wp:gutenverse/social-share --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->',
);
