<?php
/**
 * Gutenverse About content.
 */
return array(
	'title'      => __( 'Gutenverse About', 'photology' ),
	'categories' => array( 'photology-gutenverse' ),
	'content'    => '
            <!-- wp:gutenverse/section {"width":"1170","gap":"no","elementId":"guten-5e9nnt","verticalAlign":"center","background":{"type":"default","color":""},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"left":"10","right":"10","top":"80","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","left":"10","right":"10"}}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
            <div class="section-wrapper" data-id="5e9nnt"><script>var top5e9nnt = {"Desktop":{"point":"0","unit":"px"}};var bottom5e9nnt = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-5e9nnt layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":48.6,"Tablet":100},"elementId":"guten-LLkRjW","background":{"type":"default","image":{"Desktop":{"id":25,"image":"' . esc_url( PHOTOLOGY_URI ) . '/assets/img/man-person-camera-photography-photographer-male-81765-pxhere.com.jpg"}},"position":{"Desktop":"center center"},"size":{"Desktop":"cover"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[]}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-LLkRjW"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="LLkRjW"><script>var topLLkRjW = {"Desktop":{"point":"0","unit":"px"}};var bottomLLkRjW = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-de8ef1","space":{"Desktop":{"unit":"px","point":"450"},"Mobile":{"point":"315","unit":"px"},"Tablet":{"point":"","unit":"px"}}} -->
            <div class="guten-element guten-spacer guten-de8ef1"></div>
            <!-- /wp:gutenverse/spacer --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":51.4,"Tablet":100,"Mobile":null},"elementId":"guten-hm22ZI","margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"60"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"left":"","top":"20","right":"","bottom":""}}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-hm22ZI"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="hm22ZI"><script>var tophm22ZI = {"Desktop":{"point":"0","unit":"px"}};var bottomhm22ZI = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-2W1hqH","color":{"r":52,"g":51,"b":51,"a":1},"typography":{"font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"point":"38","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"spacing":{"Desktop":""},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.3"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"slow"}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-2W1hqH animated guten-element-hide slow desktop-fadeInRight">Welcome To Photology</h2>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/heading {"elementId":"guten-VP1Pdh","color":{"r":248,"g":248,"b":248,"a":1},"typography":{"font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"point":"140","unit":"px"},"Tablet":{"point":"80","unit":"px"},"Mobile":{"point":"40","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.1"}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"-1"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"slow"},"positioningType":{"Desktop":"inline"},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":""}},"positioningTop":{"Desktop":{"unit":"%","point":"-11"},"Tablet":{"point":"-20","unit":"px"},"Mobile":{"point":"-17","unit":"px"}}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-VP1Pdh animated guten-element-hide slow desktop-fadeInLeft">About</h2>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/text-editor {"elementId":"guten-wb6sWe","textColor":{"r":139,"g":139,"b":139,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"}} -->
            <div class="guten-element gutenverse-text-editor guten-wb6sWe"><div class="text-content-inner"><!-- wp:paragraph -->
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris </p>
            <!-- /wp:paragraph -->
            
            <!-- wp:gutenverse/section {"gap":"no","elementId":"guten-1SUHJi","background":{"type":"default","color":{"r":248,"g":248,"b":248,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"left":{"type":"solid","color":{"r":192,"g":177,"b":157,"a":1},"width":"5"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"60","bottom":"20","left":"30"}},"Mobile":{"unit":"px","dimension":{"right":"20"}}}} -->
            <div class="section-wrapper" data-id="1SUHJi"><script>var top1SUHJi = {"Desktop":{"point":"0","unit":"px"}};var bottom1SUHJi = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-1SUHJi layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-hllSXT","horizontalAlign":{"Desktop":"default","Tablet":"default","Mobile":"default"},"margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-hllSXT"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="hllSXT"><script>var tophllSXT = {"Desktop":{"point":"0","unit":"px"}};var bottomhllSXT = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-BEjv11","typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"style":"italic","lineHeight":{"Desktop":{"unit":"em","point":""}},"weight":"300"},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]},"zIndex":{"Desktop":"2"}} -->
            <div class="guten-element gutenverse-text-editor guten-BEjv11"><div class="text-content-inner"><!-- wp:paragraph -->
            <p>Photography is a way of feeling, of touching, of loving. What you have caught on film is captured forever. It remembers little things, long after you have forgotten everything</p>
            <!-- /wp:paragraph --></div></div>
            <!-- /wp:gutenverse/text-editor -->
            
            <!-- wp:gutenverse/icon {"elementId":"guten-GLgqvo","icon":"gtn gtn-quote-light","iconColorOne":{"r":255,"g":255,"b":255,"a":0.01},"iconSize":{"Desktop":{"point":"100","unit":"px"},"Mobile":{"point":"72","unit":"px"}},"iconColorTwo":{"r":241,"g":241,"b":241,"a":1},"iconShape":"custom","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"zIndex":{"Desktop":"0"},"positioningType":{"Desktop":"inline"},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":"80"},"Mobile":{"point":"183","unit":"px"}},"positioningRight":{"Desktop":{"point":"","unit":"px"}},"positioningTop":{"Desktop":{"unit":"%","point":"-30"},"Tablet":{"point":"","unit":"px"},"Mobile":{"unit":"%","point":"39"}}} -->
            <div class="wp-block-gutenverse-icon guten-element guten-GLgqvo guten-icon"><a class="guten-icon-wrapper custom stacked" href="#"><i class="gtn gtn-quote-light"></i></a></div>
            <!-- /wp:gutenverse/icon --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section --></div></div>
            <!-- /wp:gutenverse/text-editor -->
            
            <!-- wp:gutenverse/progress-bar {"elementId":"guten-hbCx04","title":"Photography","percentage":"92","barColor":{"r":244,"g":244,"b":244,"a":1},"trackColor":{"r":145,"g":108,"b":61,"a":1},"trackHeight":{"Desktop":"10"},"barRadius":{"Desktop":[],"Mobile":[]},"trackRadius":{"Desktop":[],"Mobile":[]},"barPadding":{"Desktop":[],"Mobile":[]},"barMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"r":52,"g":51,"b":51,"a":1},"titleTypography":{"font":{"label":"Prata","value":"Prata","type":"google"},"weight":"300","size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"spacing":{"Desktop":"0.09"}},"percentColor":{"r":139,"g":139,"b":139,"a":1},"percentTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Mobile":{"point":"14","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]}} -->
            <div class="guten-element guten-progress-bar guten-hbCx04"><div class="progress-group"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title">Photography</span></div><div class="skill-bar"><div class="skill-track" data-width="92" data-duration="3500"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
            <!-- /wp:gutenverse/progress-bar -->
            
            <!-- wp:gutenverse/progress-bar {"elementId":"guten-T9T8GR","title":"Videography","percentage":"89","barColor":{"r":244,"g":244,"b":244,"a":1},"trackColor":{"r":145,"g":108,"b":61,"a":1},"trackHeight":{"Desktop":"10"},"barRadius":{"Desktop":[]},"trackRadius":{"Desktop":[]},"barPadding":{"Desktop":[]},"barMargin":{"Desktop":[]},"titleColor":{"r":52,"g":51,"b":51,"a":1},"titleTypography":{"font":{"label":"Prata","value":"Prata","type":"google"},"weight":"300","size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"spacing":{"Desktop":"0.09"}},"percentColor":{"r":139,"g":139,"b":139,"a":1},"percentTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Mobile":{"point":"14","unit":"px"}}}} -->
            <div class="guten-element guten-progress-bar guten-T9T8GR"><div class="progress-group"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title">Videography</span></div><div class="skill-bar"><div class="skill-track" data-width="89" data-duration="3500"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
            <!-- /wp:gutenverse/progress-bar --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->',
);
