<?php
/**
 * Gutenverse Hero content.
 */
return array(
	'title'      => __( 'Gutenverse Hero', 'photology' ),
	'categories' => array( 'photology-gutenverse' ),
	'content'    => '
            <!-- wp:gutenverse/section {"width":"1170","elementId":"guten-P6sVWZ","background":{"type":"default","image":{"Desktop":{"id":52,"image":"' . esc_url( PHOTOLOGY_URI ) . '/assets/img/man-camera-photography-photographer-lens-reflex-camera-60417-pxhere.com.jpg"}},"position":{"Desktop":"top center"},"size":{"Desktop":"cover"},"repeat":{"Desktop":"no-repeat"},"yposition":{"Desktop":{"point":"","unit":"px"}},"xposition":{"Desktop":{"point":"","unit":"px"}}},"backgroundOverlay":{"type":"default","color":{"r":8,"g":8,"b":8,"a":1},"gradientColor":[{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":3,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0)","id":7,"offset":"0.107","active":false},{"color":"rgba(255, 255, 255, 0)","active":true,"id":6,"offset":"0.190"},{"color":"rgba(255, 255, 255, 0)","active":false,"id":5,"offset":"0.293"},{"color":"rgba(255, 255, 255, 0)","active":false,"id":4,"offset":"0.937"}],"gradientType":"linear","gradientAngle":270},"opacity":"0.7","margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"300","bottom":"220"}},"Tablet":{"unit":"px","dimension":{"top":"220","bottom":"120","right":"10","left":"10"}}}} -->
            <div class="section-wrapper" data-id="P6sVWZ"><script>var topP6sVWZ = {"Desktop":{"point":"0","unit":"px"}};var bottomP6sVWZ = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-P6sVWZ layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":55.99,"Tablet":100},"elementId":"guten-91Fk0O","margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":[]}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-91Fk0O"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="91Fk0O"><script>var top91Fk0O = {"Desktop":{"point":"0","unit":"px"}};var bottom91Fk0O = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-XvGz0E","type":1,"color":{"r":209,"g":200,"b":187,"a":1},"typography":{"font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"point":"60","unit":"px"},"Mobile":{"point":"31","unit":"px"}},"weight":"400","spacing":{"Desktop":""},"transform":"default","decoration":"none","style":"normal","lineHeight":{"Desktop":{"unit":"em","point":"1.3"}}},"background":{"type":"default"},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
            <h1 class="wp-block-gutenverse-heading guten-element guten-XvGz0E animated guten-element-hide desktop-fadeInLeft">Photography is the Art of Catching Memoriess</h1>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/text-editor {"elementId":"guten-0iCbAc","textColor":{"r":194,"g":186,"b":176,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"240","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"slow"}} -->
            <div class="guten-element gutenverse-text-editor guten-0iCbAc animated guten-element-hide slow desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore</p>
            <!-- /wp:paragraph --></div></div>
            <!-- /wp:gutenverse/text-editor -->
            
            <!-- wp:gutenverse/button {"elementId":"guten-BTgZlT","content":"View Portfolio","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"20","right":"25","bottom":"20","left":"25"}}},"buttonBackground":{"type":"default","color":{"r":145,"g":108,"b":61,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"slow","delay":"40"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.2"},"weight":"400"},"hoverTextColor":{"r":11,"g":11,"b":11,"a":1}} -->
            <div class="guten-element guten-button-wrapper guten-BTgZlT"><a class="guten-button animated guten-element-hide slow desktop-fadeInLeft guten-button-sm" href="#"><span>View Portfolio</span></a></div>
            <!-- /wp:gutenverse/button --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":44.01,"Mobile":null},"elementId":"guten-lpET5f","margin":{"Mobile":[]},"padding":{"Mobile":[]},"hideMobile":true} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-lpET5f hide-mobile"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="lpET5f"><script>var toplpET5f = {"Desktop":{"point":"0","unit":"px"}};var bottomlpET5f = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->',
);
