<?php
/**
 * Gutenverse Benefits content.
 */
return array(
	'title'      => __( 'Gutenverse Benefits', 'photology' ),
	'categories' => array( 'photology-gutenverse' ),
	'content'    => '
            <!-- wp:gutenverse/section {"width":"1170","gap":"no","elementId":"guten-5e9nnt","verticalAlign":"center","background":{"type":"default","color":{"r":248,"g":248,"b":248,"a":1}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"left":"10","right":"10","top":"80","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","left":"10","right":"10"}}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
            <div class="section-wrapper" data-id="5e9nnt"><script>var top5e9nnt = {"Desktop":{"point":"0","unit":"px"}};var bottom5e9nnt = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-5e9nnt layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":51.4,"Tablet":100},"elementId":"guten-hm22ZI","margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"60","bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"left":"","top":"20","right":"","bottom":""}}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-hm22ZI"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="hm22ZI"><script>var tophm22ZI = {"Desktop":{"point":"0","unit":"px"}};var bottomhm22ZI = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-2W1hqH","color":{"r":52,"g":51,"b":51,"a":1},"typography":{"font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"point":"38","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"spacing":{"Desktop":""},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.3"}}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"2"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"slow"}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-2W1hqH animated guten-element-hide slow desktop-fadeInLeft">Why Choose Us</h2>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/heading {"elementId":"guten-VP1Pdh","color":{"r":240,"g":240,"b":240,"a":1},"typography":{"font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"point":"140","unit":"px"},"Mobile":{"point":"40","unit":"px"},"Tablet":{"point":"80","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.1"}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"0"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"slow"},"positioningType":{"Desktop":"inline"},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":"-36"},"Mobile":{"point":"0","unit":"px"},"Tablet":{"point":"-8","unit":"px"}},"positioningRight":{"Mobile":{"point":"","unit":"px"}},"positioningTop":{"Desktop":{"unit":"%","point":"-4"},"Mobile":{"point":"-22","unit":"px"},"Tablet":{"point":"-33","unit":"px"}}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-VP1Pdh animated guten-element-hide slow desktop-fadeInRight">BENEFITS</h2>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/text-editor {"elementId":"guten-wb6sWe","textColor":{"r":139,"g":139,"b":139,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"}} -->
            <div class="guten-element gutenverse-text-editor guten-wb6sWe"><div class="text-content-inner"><!-- wp:paragraph -->
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris </p>
            <!-- /wp:paragraph --></div></div>
            <!-- /wp:gutenverse/text-editor -->
            
            <!-- wp:gutenverse/icon-box {"elementId":"guten-W6b6Te","title":"High Quality","titleTag":"h3","icon":"gtn gtn-photo-camera1-light","iconPosition":"left","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"right":"10"}}},"iconColor":{"r":255,"g":255,"b":255,"a":1},"iconBgColor":{"r":145,"g":108,"b":61,"a":1},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"titlePadding":{"Desktop":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"r":52,"g":51,"b":51,"a":1},"titleTypography":{"font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"}},"weight":"300"},"descMargin":{"Desktop":[],"Mobile":[]},"descColor":{"r":139,"g":139,"b":139,"a":1},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]}} -->
            <div class="guten-element guten-W6b6Te guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-photo-camera1-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">High Quality</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div></div></div>
            <!-- /wp:gutenverse/icon-box -->
            
            <!-- wp:gutenverse/icon-box {"elementId":"guten-FfWB1v","title":"Timelesss Style","titleTag":"h3","icon":"gtn gtn-magic-wand-light","iconPosition":"left","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"right":"10"}}},"iconColor":{"r":255,"g":255,"b":255,"a":1},"iconBgColor":{"r":145,"g":108,"b":61,"a":1},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"titlePadding":{"Desktop":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"r":52,"g":51,"b":51,"a":1},"titleTypography":{"font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"}},"weight":"300"},"descMargin":{"Desktop":[],"Mobile":[]},"descColor":{"r":139,"g":139,"b":139,"a":1},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"}} -->
            <div class="guten-element guten-FfWB1v guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-magic-wand-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Timelesss Style</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div></div></div>
            <!-- /wp:gutenverse/icon-box -->
            
            <!-- wp:gutenverse/icon-box {"elementId":"guten-mdsUZ7","title":"Unlimited Time","titleTag":"h3","icon":"gtn gtn-clock11-light","iconPosition":"left","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"right":"10"}}},"iconColor":{"r":255,"g":255,"b":255,"a":1},"iconBgColor":{"r":145,"g":108,"b":61,"a":1},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"titlePadding":{"Desktop":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"r":52,"g":51,"b":51,"a":1},"titleTypography":{"font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"}},"weight":"300"},"descMargin":{"Desktop":[],"Mobile":[]},"descColor":{"r":139,"g":139,"b":139,"a":1},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"}} -->
            <div class="guten-element guten-mdsUZ7 guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-clock11-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Unlimited Time</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div></div></div>
            <!-- /wp:gutenverse/icon-box -->
            
            <!-- wp:gutenverse/icon-box {"elementId":"guten-3gFfL6","title":"Experience","titleTag":"h3","icon":"gtn gtn-badge","iconPosition":"left","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"right":"10"}}},"iconColor":{"r":255,"g":255,"b":255,"a":1},"iconBgColor":{"r":145,"g":108,"b":61,"a":1},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"titlePadding":{"Desktop":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"r":52,"g":51,"b":51,"a":1},"titleTypography":{"font":{"label":"Prata","value":"Prata","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Mobile":{"point":"","unit":"px"}},"weight":"300"},"descMargin":{"Desktop":[],"Mobile":[]},"descColor":{"r":139,"g":139,"b":139,"a":1},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"}} -->
            <div class="guten-element guten-3gFfL6 guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-badge"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Experience</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div></div></div>
            <!-- /wp:gutenverse/icon-box --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":48.6,"Tablet":100},"elementId":"guten-LLkRjW","background":{"type":"default","image":{"Desktop":{"id":25,"image":"' . esc_url( PHOTOLOGY_URI ) . '/assets/img/man-person-camera-photography-photographer-male-81765-pxhere.com.jpg"}},"position":{"Desktop":"center center"},"size":{"Desktop":"cover"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"10","bottom":"0","left":"10"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-LLkRjW"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="LLkRjW"><script>var topLLkRjW = {"Desktop":{"point":"0","unit":"px"}};var bottomLLkRjW = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-de8ef1","space":{"Desktop":{"unit":"px","point":"625"},"Mobile":{"point":"340","unit":"px"}}} -->
            <div class="guten-element guten-spacer guten-de8ef1"></div>
            <!-- /wp:gutenverse/spacer --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->',
);
