<?php
/**
 * Gutenverse Description content.
 */
return array(
	'title'      => __( 'Gutenverse Description', 'financio' ),
	'categories' => array( 'financio-gutenverse' ),
	'content'    => '
            <!-- wp:gutenverse/section {"width":"1170","gap":"no","elementId":"guten-hWOsrW","verticalAlign":"center","background":{"type":"default","color":""},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"100","left":"20","right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"100","left":"20"}}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
            <div class="section-wrapper" data-id="hWOsrW"><script>var tophWOsrW = {"Desktop":{"point":"0","unit":"px"}};var bottomhWOsrW = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-hWOsrW layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":51.4,"Tablet":100},"elementId":"guten-lTdEKL","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","right":"70"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-lTdEKL"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="lTdEKL"><script>var toplTdEKL = {"Desktop":{"point":"0","unit":"px"}};var bottomlTdEKL = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-B5Pvel","color":{"r":4,"g":183,"b":114,"a":1},"typography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"spacing":{"Desktop":""},"weight":"500","lineHeight":{"Desktop":{"unit":"em","point":"1.3"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"slow"}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-B5Pvel animated guten-element-hide slow desktop-fadeInLeft">Who We Are</h2>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/heading {"elementId":"guten-LxkPRr","color":{"r":14,"g":35,"b":35,"a":1},"typography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"32","unit":"px"},"Mobile":{"point":"23","unit":"px"}},"spacing":{"Desktop":""},"weight":"500","lineHeight":{"Desktop":{"unit":"em","point":"1.3"}}},"margin":{"Tablet":{"unit":"px","dimension":{"right":"80"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-LxkPRr">We Keep Your Finance Safe And Ensure High Availability</h2>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/text-editor {"elementId":"guten-mWWWOZ","textColor":{"r":121,"g":130,"b":144,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Mobile":[]}} -->
            <div class="guten-element gutenverse-text-editor guten-mWWWOZ"><div class="text-content-inner"><!-- wp:paragraph -->
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris</p>
            <!-- /wp:paragraph -->
            
            <!-- wp:gutenverse/progress-bar {"elementId":"guten-Z3dpAf","title":"Investment Planning","percentage":"90","barColor":{"r":243,"g":243,"b":243,"a":1},"trackColor":{"r":4,"g":183,"b":114,"a":1},"trackHeight":{"Desktop":"12"},"barRadius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"trackRadius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"barPadding":{"Desktop":[]},"barMargin":{"Desktop":[]},"titleColor":{"r":69,"g":79,"b":95,"a":1},"titleTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"percentColor":{"r":121,"g":130,"b":144,"a":1},"percentTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"}} -->
            <div class="guten-element guten-progress-bar guten-Z3dpAf"><div class="progress-group"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title">Investment Planning</span></div><div class="skill-bar"><div class="skill-track" data-width="90" data-duration="3500"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
            <!-- /wp:gutenverse/progress-bar -->
            
            <!-- wp:gutenverse/progress-bar {"elementId":"guten-We5WqD","title":"Accounts Outsourcing","percentage":"92","barColor":{"r":243,"g":243,"b":243,"a":1},"trackColor":{"r":4,"g":183,"b":114,"a":1},"trackHeight":{"Desktop":"12"},"barRadius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"trackRadius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"barPadding":{"Desktop":[]},"barMargin":{"Desktop":[]},"titleColor":{"r":69,"g":79,"b":95,"a":1},"titleTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"percentColor":{"r":121,"g":130,"b":144,"a":1},"percentTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"}} -->
            <div class="guten-element guten-progress-bar guten-We5WqD"><div class="progress-group"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title">Accounts Outsourcing</span></div><div class="skill-bar"><div class="skill-track" data-width="92" data-duration="3500"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
            <!-- /wp:gutenverse/progress-bar -->
            
            <!-- wp:gutenverse/progress-bar {"elementId":"guten-2epFBl","title":"Business Taxation","percentage":"91","barColor":{"r":243,"g":243,"b":243,"a":1},"trackColor":{"r":4,"g":183,"b":114,"a":1},"trackHeight":{"Desktop":"12"},"barRadius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"trackRadius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"barPadding":{"Desktop":[]},"barMargin":{"Desktop":[]},"titleColor":{"r":69,"g":79,"b":95,"a":1},"titleTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"percentColor":{"r":121,"g":130,"b":144,"a":1},"percentTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"}} -->
            <div class="guten-element guten-progress-bar guten-2epFBl"><div class="progress-group"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title">Business Taxation</span></div><div class="skill-bar"><div class="skill-track" data-width="91" data-duration="3500"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
            <!-- /wp:gutenverse/progress-bar -->
            
            <!-- wp:gutenverse/progress-bar {"elementId":"guten-5tnlk8","title":"Payroll \u0026 Salary","percentage":"89","barColor":{"r":243,"g":243,"b":243,"a":1},"trackColor":{"r":4,"g":183,"b":114,"a":1},"trackHeight":{"Desktop":"12"},"barRadius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"trackRadius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"barPadding":{"Desktop":[]},"barMargin":{"Desktop":[]},"titleColor":{"r":69,"g":79,"b":95,"a":1},"titleTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"percentColor":{"r":121,"g":130,"b":144,"a":1},"percentTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"}} -->
            <div class="guten-element guten-progress-bar guten-5tnlk8"><div class="progress-group"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title">Payroll &amp; Salary</span></div><div class="skill-bar"><div class="skill-track" data-width="89" data-duration="3500"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
            <!-- /wp:gutenverse/progress-bar --></div></div>
            <!-- /wp:gutenverse/text-editor --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":48.6,"Tablet":100,"Mobile":null},"elementId":"guten-KpeFEu","background":{"type":"default","image":{"Desktop":{"id":214,"image":"' . esc_url( FINANCIO_URI ) . '/assets/img/action-american-beverage-brainstorming-business-caucasian-1445431-pxhere.com.jpg"}},"position":{"Desktop":"center center"},"size":{"Desktop":"cover"},"xposition":{"Desktop":{"unit":"px","point":""}},"yposition":{"Desktop":{"point":"","unit":"px"}},"repeat":{"Desktop":"no-repeat"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"60"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"slow"}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-KpeFEu animated guten-element-hide slow desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="KpeFEu"><script>var topKpeFEu = {"Desktop":{"point":"0","unit":"px"}};var bottomKpeFEu = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-9eGLMg","space":{"Desktop":{"point":"488","unit":"px"},"Mobile":{"point":"321","unit":"px"}}} -->
            <div class="guten-element guten-spacer guten-9eGLMg"></div>
            <!-- /wp:gutenverse/spacer --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->',
);
