<?php
/**
 * Gutenverse Feature content.
 */
return array(
	'title'      => __( 'Gutenverse Feature', 'financio' ),
	'categories' => array( 'financio-gutenverse' ),
	'content'    => ' 
            <!-- wp:gutenverse/section {"width":"1170","gap":"no","elementId":"guten-uL3WNu","background":{"type":"default","color":"","image":{"Desktop":{"id":74,"image":"' . esc_url( FINANCIO_URI ) . '/assets/img/achievement-analysis-brainstorming-business-business-plan-caucasian-1448601-pxhere.com.jpg"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"default","color":{"r":5,"g":5,"b":5,"a":1}},"opacity":"0.8","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"80"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"left":"20","right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
            <div class="section-wrapper" data-id="uL3WNu"><script>var topuL3WNu = {"Desktop":{"point":"0","unit":"px"}};var bottomuL3WNu = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-uL3WNu layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-Tf7s4t"} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-Tf7s4t"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Tf7s4t"><script>var topTf7s4t = {"Desktop":{"point":"0","unit":"px"}};var bottomTf7s4t = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-VibiRx","type":5,"textAlign":{"Desktop":"center","Tablet":"center","Mobile":"left"},"color":{"r":4,"g":183,"b":114,"a":1},"typography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"500"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"slow"}} -->
            <h5 class="wp-block-gutenverse-heading guten-element guten-VibiRx animated guten-element-hide slow desktop-fadeInUp">Our Service</h5>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/heading {"elementId":"guten-gFYC7c","textAlign":{"Desktop":"center","Tablet":"center","Mobile":"left"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"32","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"500"}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-gFYC7c">What Service We Offer</h2>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/text-editor {"elementId":"guten-3RPwN7","alignment":{"Desktop":"center","Tablet":"center","Mobile":"left"},"textColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"26","left":"26"}},"Tablet":{"unit":"%","dimension":{"top":"0","right":"12","bottom":"0","left":"12"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
            <div class="guten-element gutenverse-text-editor guten-3RPwN7"><div class="text-content-inner"><!-- wp:paragraph -->
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
            <!-- /wp:paragraph --></div></div>
            <!-- /wp:gutenverse/text-editor -->
            
            <!-- wp:gutenverse/section {"width":"1170","isChild":true,"gap":"no","elementId":"guten-2IMNVq","margin":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"slow"}} -->
            <div class="section-wrapper" data-id="2IMNVq"><script>var top2IMNVq = {"Desktop":{"point":"0","unit":"px"}};var bottom2IMNVq = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-2IMNVq animated guten-element-hide slow desktop-fadeInUp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-XBu5sY","margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-XBu5sY"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="XBu5sY"><script>var topXBu5sY = {"Desktop":{"point":"0","unit":"px"}};var bottomXBu5sY = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-9Xt3hx","title":"Investment Planning","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ","icon":"gtn gtn-invest-light","iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"50","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerBackground":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBoxShadow":{"horizontal":"0","vertical":"3","blur":"15","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"r":255,"g":255,"b":255,"a":1},"iconBgColor":{"r":5,"g":183,"b":114,"a":1},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleColor":{"r":14,"g":35,"b":35,"a":1},"titleTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"r":121,"g":130,"b":144,"a":1},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}}}} -->
            <div class="guten-element guten-9Xt3hx guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-invest-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Investment Planning</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore </p><!-- wp:gutenverse/button {"elementId":"guten-F9jDe9","content":"Read More","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":232,"g":105,"b":105,"a":0.01}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"10"},"iconSize":{"point":"12","unit":"px","Desktop":{"point":"14","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"color":{"r":4,"g":183,"b":114,"a":1},"iconColor":{"r":4,"g":183,"b":114,"a":1},"typography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"500"}} -->
            <div class="guten-element guten-button-wrapper guten-F9jDe9"><a class="guten-button guten-button-sm" href="#"><span>Read More</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
            <!-- /wp:gutenverse/button --></div></div></div>
            <!-- /wp:gutenverse/icon-box --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-PFbrIW","margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-PFbrIW"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="PFbrIW"><script>var topPFbrIW = {"Desktop":{"point":"0","unit":"px"}};var bottomPFbrIW = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-CHNSY2","title":"Audit \u0026amp; Assurance","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ","icon":"gtn gtn-consut2-light","iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"50","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerBackground":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBoxShadow":{"horizontal":"0","vertical":"3","blur":"15","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"r":255,"g":255,"b":255,"a":1},"iconBgColor":{"r":5,"g":183,"b":114,"a":1},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleColor":{"r":14,"g":35,"b":35,"a":1},"titleTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"r":121,"g":130,"b":144,"a":1},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}}}} -->
            <div class="guten-element guten-CHNSY2 guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-consut2-light"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Audit &amp; Assurance</h2><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore </p><!-- wp:gutenverse/button {"elementId":"guten-9MhRQl","content":"Read More","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":232,"g":105,"b":105,"a":0.01}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"10"},"iconSize":{"point":"12","unit":"px","Desktop":{"point":"14","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"color":{"r":4,"g":183,"b":114,"a":1},"iconColor":{"r":4,"g":183,"b":114,"a":1},"typography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"500"}} -->
            <div class="guten-element guten-button-wrapper guten-9MhRQl"><a class="guten-button guten-button-sm" href="#"><span>Read More</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
            <!-- /wp:gutenverse/button --></div></div></div>
            <!-- /wp:gutenverse/icon-box --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-wgjxWE","margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-wgjxWE"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="wgjxWE"><script>var topwgjxWE = {"Desktop":{"point":"0","unit":"px"}};var bottomwgjxWE = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-jR8kCP","title":"Business Taxation","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ","icon":"gtn gtn-business-light","iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"50","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerBackground":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBoxShadow":{"horizontal":"0","vertical":"3","blur":"15","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"r":255,"g":255,"b":255,"a":1},"iconBgColor":{"r":5,"g":183,"b":114,"a":1},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleColor":{"r":14,"g":35,"b":35,"a":1},"titleTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"r":121,"g":130,"b":144,"a":1},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}}}} -->
            <div class="guten-element guten-jR8kCP guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-business-light"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Business Taxation</h2><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore </p><!-- wp:gutenverse/button {"elementId":"guten-rkHzRF","content":"Read More","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":232,"g":105,"b":105,"a":0.01}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"10"},"iconSize":{"point":"12","unit":"px","Desktop":{"point":"14","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"color":{"r":4,"g":183,"b":114,"a":1},"iconColor":{"r":4,"g":183,"b":114,"a":1},"typography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"500"}} -->
            <div class="guten-element guten-button-wrapper guten-rkHzRF"><a class="guten-button guten-button-sm" href="#"><span>Read More</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
            <!-- /wp:gutenverse/button --></div></div></div>
            <!-- /wp:gutenverse/icon-box --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->
            
            <!-- wp:gutenverse/section {"width":"1170","isChild":true,"gap":"no","elementId":"guten-z6ZvzV","margin":{"Desktop":{"unit":"px","dimension":{"top":"40","bottom":"-80"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"-40","left":"0"}},"Tablet":[]},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"slow"}} -->
            <div class="section-wrapper" data-id="z6ZvzV"><script>var topz6ZvzV = {"Desktop":{"point":"0","unit":"px"}};var bottomz6ZvzV = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-z6ZvzV animated guten-element-hide slow desktop-fadeInUp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-SENnBD","margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-SENnBD"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="SENnBD"><script>var topSENnBD = {"Desktop":{"point":"0","unit":"px"}};var bottomSENnBD = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-Yozt5j","title":"Accounts Outsourcing","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ","icon":"gtn gtn-coins-1-light","iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"50","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerBackground":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBoxShadow":{"horizontal":"0","vertical":"3","blur":"15","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"r":255,"g":255,"b":255,"a":1},"iconBgColor":{"r":5,"g":183,"b":114,"a":1},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleColor":{"r":14,"g":35,"b":35,"a":1},"titleTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"r":121,"g":130,"b":144,"a":1},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}}}} -->
            <div class="guten-element guten-Yozt5j guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-coins-1-light"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Accounts Outsourcing</h2><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore </p><!-- wp:gutenverse/button {"elementId":"guten-VpKUAo","content":"Read More","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":232,"g":105,"b":105,"a":0.01}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"10"},"iconSize":{"point":"12","unit":"px","Desktop":{"point":"14","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"color":{"r":4,"g":183,"b":114,"a":1},"iconColor":{"r":4,"g":183,"b":114,"a":1},"typography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"500"}} -->
            <div class="guten-element guten-button-wrapper guten-VpKUAo"><a class="guten-button guten-button-sm" href="#"><span>Read More</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
            <!-- /wp:gutenverse/button --></div></div></div>
            <!-- /wp:gutenverse/icon-box --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-pye0x1","margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-pye0x1"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="pye0x1"><script>var toppye0x1 = {"Desktop":{"point":"0","unit":"px"}};var bottompye0x1 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-STFGXb","title":"Payroll \u0026amp; Salary","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ","icon":"gtn gtn-commerce-light","iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"50","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerBackground":{"type":"default","color":{"r":4,"g":183,"b":114,"a":1}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"r":5,"g":183,"b":114,"a":1},"iconBgColor":{"r":255,"g":255,"b":255,"a":1},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"titleMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleColor":{"r":255,"g":255,"b":255,"a":1},"titleTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"r":255,"g":255,"b":255,"a":1},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}}}} -->
            <div class="guten-element guten-STFGXb guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-commerce-light"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Payroll &amp; Salary</h2><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore </p><!-- wp:gutenverse/button {"elementId":"guten-WfGJxZ","content":"Read More","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":232,"g":105,"b":105,"a":0.01}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"10"},"iconSize":{"point":"12","unit":"px","Desktop":{"point":"14","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"color":{"r":255,"g":255,"b":255,"a":1},"iconColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"500"}} -->
            <div class="guten-element guten-button-wrapper guten-WfGJxZ"><a class="guten-button guten-button-sm" href="#"><span>Read More</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
            <!-- /wp:gutenverse/button --></div></div></div>
            <!-- /wp:gutenverse/icon-box --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-cPlXht","margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-cPlXht"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="cPlXht"><script>var topcPlXht = {"Desktop":{"point":"0","unit":"px"}};var bottomcPlXht = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-B4VTaV","title":"Loan Management","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ","icon":"gtn gtn-loan-light","iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"50","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"30","bottom":"40","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerBackground":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBoxShadow":{"horizontal":"0","vertical":"3","blur":"15","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"r":255,"g":255,"b":255,"a":1},"iconBgColor":{"r":5,"g":183,"b":114,"a":1},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleColor":{"r":14,"g":35,"b":35,"a":1},"titleTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"r":121,"g":130,"b":144,"a":1},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}}}} -->
            <div class="guten-element guten-B4VTaV guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-loan-light"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Loan Management</h2><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore </p><!-- wp:gutenverse/button {"elementId":"guten-HPkW4A","content":"Read More","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":232,"g":105,"b":105,"a":0.01}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"10"},"iconSize":{"point":"12","unit":"px","Desktop":{"point":"14","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"color":{"r":4,"g":183,"b":114,"a":1},"iconColor":{"r":4,"g":183,"b":114,"a":1},"typography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"500"}} -->
            <div class="guten-element guten-button-wrapper guten-HPkW4A"><a class="guten-button guten-button-sm" href="#"><span>Read More</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
            <!-- /wp:gutenverse/button --></div></div></div>
            <!-- /wp:gutenverse/icon-box --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->',
);
