<?php
/**
 * Gutenverse Team content.
 */
return array(
	'title'      => __( 'Gutenverse Team', 'financio' ),
	'categories' => array( 'financio-gutenverse' ),
	'content'    => '
            <!-- wp:gutenverse/section {"elementId":"guten-jE5fRc","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40"}}}} -->
            <div class="section-wrapper" data-id="jE5fRc"><script>var topjE5fRc = {"Desktop":{"point":"0","unit":"px"}};var bottomjE5fRc = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-jE5fRc layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-KhvMhz","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-KhvMhz"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="KhvMhz"><script>var topKhvMhz = {"Desktop":{"point":"0","unit":"px"}};var bottomKhvMhz = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-dbmFbD","type":5,"textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"r":4,"g":183,"b":114,"a":1},"typography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"500"},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"slow"}} -->
            <h5 class="wp-block-gutenverse-heading guten-element guten-dbmFbD animated guten-element-hide slow desktop-fadeInUp">Our Team</h5>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/heading {"elementId":"guten-bsCdV0","textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"r":14,"g":35,"b":35,"a":1},"typography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"32","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"500"}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-bsCdV0">Meet With Professional Team</h2>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/text-editor {"elementId":"guten-0vkpId","alignment":{"Desktop":"center","Tablet":"center","Mobile":"center"},"textColor":{"r":121,"g":130,"b":144,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"26","left":"26"}},"Tablet":{"unit":"%","dimension":{"right":"12","left":"12"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
            <div class="guten-element gutenverse-text-editor guten-0vkpId"><div class="text-content-inner"><!-- wp:paragraph -->
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
            <!-- /wp:paragraph --></div></div>
            <!-- /wp:gutenverse/text-editor -->
            
            <!-- wp:gutenverse/section {"width":"1170","isChild":true,"gap":"no","elementId":"guten-3FX1Y1","margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}},"Mobile":{"unit":"px","dimension":{"top":"20"}},"Tablet":[]},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"slow"}} -->
            <div class="section-wrapper" data-id="3FX1Y1"><script>var top3FX1Y1 = {"Desktop":{"point":"0","unit":"px"}};var bottom3FX1Y1 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-3FX1Y1 animated guten-element-hide slow desktop-fadeInUp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-lSYSih","margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-lSYSih"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="lSYSih"><script>var toplSYSih = {"Desktop":{"point":"0","unit":"px"}};var bottomlSYSih = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-sncPyv","profileType":"overlay","overlayType":"default","overlayPosition":"bottom","src":{"id":90,"image":"' . esc_url( FINANCIO_URI ) . '/assets/img/laptop-notebook-work-hand-suit-people-1278242-pxhere.com.jpg"},"name":"Jennifer Doe","job":"Financial Advisor","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"500"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"descColor":{"r":255,"g":255,"b":255,"a":1},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"imgWidth":{"Tablet":{"point":"240","unit":"px"},"Mobile":{"unit":"%","point":"100"}},"nameSpace":{"Desktop":"6"},"jobSpace":{"Desktop":"34"},"descSpace":{"Desktop":""}} -->
            <div class="wp-block-gutenverse-team guten-element guten-team guten-sncPyv"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( FINANCIO_URI ) . '/assets/img/laptop-notebook-work-hand-suit-people-1278242-pxhere.com.jpg" alt="Jennifer Doe"/><div class="profile-body bottom"><h3 class="profile-title ">Jennifer Doe</h3><p class="profile-sub">Financial Advisor</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-LvGJKL","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"10","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"r":255,"g":255,"b":255,"a":1},"bgColor":{"r":4,"g":183,"b":114,"a":1},"hoverIconColor":{"r":4,"g":183,"b":114,"a":1},"hoverBgColor":{"r":255,"g":255,"b":255,"a":1},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":[]}} -->
            <div class="guten-element guten-social-icons guten-LvGJKL circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-lxf3Sv"} -->
            <div class="guten-element guten-social-icon guten-lxf3Sv facebook"><a id="guten-lxf3Sv"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-jSL3O7"} -->
            <div class="guten-element guten-social-icon guten-jSL3O7 twitter"><a id="guten-jSL3O7"><i class="fab fa-twitter"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-hQNLcK"} -->
            <div class="guten-element guten-social-icon guten-hQNLcK instagram"><a id="guten-hQNLcK"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon --></div>
            <!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
            <!-- /wp:gutenverse/team --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-QugB45","margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"20","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-QugB45"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="QugB45"><script>var topQugB45 = {"Desktop":{"point":"0","unit":"px"}};var bottomQugB45 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-DQMxmt","profileType":"overlay","overlayType":"default","overlayPosition":"bottom","src":{"id":98,"image":"' . esc_url( FINANCIO_URI ) . '/assets/img/suit-formal-wear-tuxedo-fashion-groom-outerwear-1545637-pxhere.com.jpg"},"name":"Jonathan Doe","job":"Financial Advisor","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"500"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"jobTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"descColor":{"r":255,"g":255,"b":255,"a":1},"alignment":{"Tablet":null},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"","bottom":"","left":""}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"2","right":"2","bottom":"2","left":"2"}},"Mobile":[]},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"imgWidth":{"Tablet":{"point":"240","unit":"px"},"Mobile":{"unit":"%","point":"100"}},"nameSpace":{"Desktop":"6"},"jobSpace":{"Desktop":"34"}} -->
            <div class="wp-block-gutenverse-team guten-element guten-team guten-DQMxmt"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( FINANCIO_URI ) . '/assets/img/suit-formal-wear-tuxedo-fashion-groom-outerwear-1545637-pxhere.com.jpg" alt="Jonathan Doe"/><div class="profile-body bottom"><h3 class="profile-title ">Jonathan Doe</h3><p class="profile-sub">Financial Advisor</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-9hrXzV","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"10","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"r":255,"g":255,"b":255,"a":1},"bgColor":{"r":4,"g":183,"b":114,"a":1},"hoverIconColor":{"r":4,"g":183,"b":114,"a":1},"hoverBgColor":{"r":255,"g":255,"b":255,"a":1},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":[]}} -->
            <div class="guten-element guten-social-icons guten-9hrXzV circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-WeoRYA"} -->
            <div class="guten-element guten-social-icon guten-WeoRYA facebook"><a id="guten-WeoRYA"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-kBOxHe"} -->
            <div class="guten-element guten-social-icon guten-kBOxHe twitter"><a id="guten-kBOxHe"><i class="fab fa-twitter"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-92PIgK"} -->
            <div class="guten-element guten-social-icon guten-92PIgK instagram"><a id="guten-92PIgK"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon --></div>
            <!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
            <!-- /wp:gutenverse/team --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-ctSVFF","margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-ctSVFF"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="ctSVFF"><script>var topctSVFF = {"Desktop":{"point":"0","unit":"px"}};var bottomctSVFF = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-Chanoy","profileType":"overlay","overlayType":"default","overlayPosition":"bottom","src":{"id":97,"image":"' . esc_url( FINANCIO_URI ) . '/assets/img/girl-young-business-businesswoman-office-stands-1456591-pxhere.com.jpg"},"name":"Nelly Cooper","job":"Financial Advisor","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"500"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"jobTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"descColor":{"r":255,"g":255,"b":255,"a":1},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"imgWidth":{"Tablet":{"point":"240","unit":"px"},"Mobile":{"unit":"%","point":"100"}},"nameSpace":{"Desktop":"6"},"jobSpace":{"Desktop":"34"}} -->
            <div class="wp-block-gutenverse-team guten-element guten-team guten-Chanoy"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( FINANCIO_URI ) . '/assets/img/girl-young-business-businesswoman-office-stands-1456591-pxhere.com.jpg" alt="Nelly Cooper"/><div class="profile-body bottom"><h3 class="profile-title ">Nelly Cooper</h3><p class="profile-sub">Financial Advisor</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-6lqnxl","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"10","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"r":255,"g":255,"b":255,"a":1},"bgColor":{"r":4,"g":183,"b":114,"a":1},"hoverIconColor":{"r":4,"g":183,"b":114,"a":1},"hoverBgColor":{"r":255,"g":255,"b":255,"a":1},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":[]}} -->
            <div class="guten-element guten-social-icons guten-6lqnxl circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-rBHf4F"} -->
            <div class="guten-element guten-social-icon guten-rBHf4F facebook"><a id="guten-rBHf4F"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-ga3LEQ"} -->
            <div class="guten-element guten-social-icon guten-ga3LEQ twitter"><a id="guten-ga3LEQ"><i class="fab fa-twitter"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-Z2k9u7"} -->
            <div class="guten-element guten-social-icon guten-Z2k9u7 instagram"><a id="guten-Z2k9u7"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon --></div>
            <!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
            <!-- /wp:gutenverse/team --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->',
);
