<?php
/**
 * Gutenverse Section 2 content.
 */
return array(
	'title'      => __( 'Gutenverse Section 2', 'financio' ),
	'categories' => array( 'financio-gutenverse' ),
	'content'    => '
            <!-- wp:gutenverse/section {"width":"1170","gap":"no","elementId":"guten-5e9nnt","verticalAlign":"center","background":{"type":"default","color":""},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"left":"10","right":"10","top":"80","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","left":"10","right":"10"}}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
            <div class="section-wrapper" data-id="5e9nnt"><script>var top5e9nnt = {"Desktop":{"point":"0","unit":"px"}};var bottom5e9nnt = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-5e9nnt layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":48.6,"Tablet":100},"elementId":"guten-LLkRjW","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-LLkRjW"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="LLkRjW"><script>var topLLkRjW = {"Desktop":{"point":"0","unit":"px"}};var bottomLLkRjW = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-zzXU48","imgSrc":{"media":{"imageId":410,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( FINANCIO_URI ) . '/assets/img/african-american-afro-american-analyzing-black-people-brainstorming-1434697-pxhere.com-150x150.jpeg","orientation":"landscape"},"medium":{"height":200,"width":300,"url":"' . esc_url( FINANCIO_URI ) . '/assets/img/african-american-afro-american-analyzing-black-people-brainstorming-1434697-pxhere.com-300x200.jpeg","orientation":"landscape"},"large":{"height":683,"width":1024,"url":"' . esc_url( FINANCIO_URI ) . '/assets/img/african-american-afro-american-analyzing-black-people-brainstorming-1434697-pxhere.com-1024x683.jpeg","orientation":"landscape"},"full":{"url":"' . esc_url( FINANCIO_URI ) . '/assets/img/african-american-afro-american-analyzing-black-people-brainstorming-1434697-pxhere.com.jpg","height":1280,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"","unit":"px"},"Tablet":{"unit":"%","point":"100"},"Mobile":{"unit":"%","point":"100"}},"height":{"Desktop":{"point":"465","unit":"px"},"Mobile":{"point":"250","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":[]}},"imageFit":{"Desktop":"cover"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"slow"}} -->
            <div class="wp-block-gutenverse-image guten-element guten-image guten-zzXU48 animated guten-element-hide slow desktop-fadeInLeft"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( FINANCIO_URI ) . '/assets/img/african-american-afro-american-analyzing-black-people-brainstorming-1434697-pxhere.com.jpg" height="1280" width="1920"/></a></div>
            <!-- /wp:gutenverse/image --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":51.4,"Tablet":100},"elementId":"guten-hm22ZI","margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"60"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"left":"","top":"20","right":"","bottom":""}}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-hm22ZI"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="hm22ZI"><script>var tophm22ZI = {"Desktop":{"point":"0","unit":"px"}};var bottomhm22ZI = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-7otlnJ","color":{"r":4,"g":183,"b":114,"a":1},"typography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"spacing":{"Desktop":""},"weight":"500","lineHeight":{"Desktop":{"unit":"em","point":"1.3"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"slow"}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-7otlnJ animated guten-element-hide slow desktop-fadeInRight">About Us</h2>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/heading {"elementId":"guten-2W1hqH","color":{"r":14,"g":35,"b":35,"a":1},"typography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"32","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"spacing":{"Desktop":""},"weight":"500","lineHeight":{"Desktop":{"unit":"em","point":"1.3"}}}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-2W1hqH">The Easiest Way to Manage Your Personal Finances</h2>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/text-editor {"elementId":"guten-wb6sWe","textColor":{"r":121,"g":130,"b":144,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"}} -->
            <div class="guten-element gutenverse-text-editor guten-wb6sWe"><div class="text-content-inner"><!-- wp:paragraph -->
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris </p>
            <!-- /wp:paragraph --></div></div>
            <!-- /wp:gutenverse/text-editor -->
            
            <!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-izGD1I","margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]}} -->
            <div class="section-wrapper" data-id="izGD1I"><script>var topizGD1I = {"Desktop":{"point":"0","unit":"px"}};var bottomizGD1I = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-izGD1I layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-cae7WS","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-cae7WS"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="cae7WS"><script>var topcae7WS = {"Desktop":{"point":"0","unit":"px"}};var bottomcae7WS = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-Yozt5j","title":"Our Vision","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor","icon":"gtn gtn-eye2-light","iconPosition":"top","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBackground":{"type":"default","color":""},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"iconColor":{"r":5,"g":183,"b":114,"a":1},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"titleMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"r":14,"g":35,"b":35,"a":1},"titleTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"descColor":{"r":121,"g":130,"b":144,"a":1},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}}}} -->
            <div class="guten-element guten-Yozt5j guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-eye2-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Our Vision</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor</p></div></div></div>
            <!-- /wp:gutenverse/icon-box --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-vxeXGf","margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"20","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-vxeXGf"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="vxeXGf"><script>var topvxeXGf = {"Desktop":{"point":"0","unit":"px"}};var bottomvxeXGf = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-oP42hc","title":"Our Mission","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor","icon":"gtn gtn-target-light","iconPosition":"top","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBackground":{"type":"default","color":""},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"iconColor":{"r":5,"g":183,"b":114,"a":1},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"titleMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"r":14,"g":35,"b":35,"a":1},"titleTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"descColor":{"r":121,"g":130,"b":144,"a":1},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}}}} -->
            <div class="guten-element guten-oP42hc guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-target-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Our Mission</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor</p></div></div></div>
            <!-- /wp:gutenverse/icon-box --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->',
);
